config/routes.rb
Rails.application.routes.draw do
  
  get 'attendance/new'
  post 'attendance/create'
  get 'attendance/index'
  get 'attendance/thankyou'
  get 'attendance/cantcome' =>"attendance#sorry"
  post 'attendance/sorrysend'
  get 'canntocome/land' => 'attendance#sorry_land'
  get '/backup' => 'attendance#backup'
  
  get 'attendance/list'
  post 'attendance/delete/:id' => "attendance#delete"
  get "/attendance/update/:id" => "attendance#update"
  post "/attendance/update/:id" => "attendance#change"

  get 'user/login' =>"user#login_page"
  post 'user/login' =>"user#login"
  post "/logout" => "user#logout"
  get "user/new" => "user#new"
  post "user/create" => "user#create"
  get "user/index" =>"user#index"

  get '/' =>"welcome#home"
  get '/land'=>"welcome#land"
  get '/place' =>'welcome#place'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    before_action :set_current_user
  
    protect_from_forgery with: :exception
  
    def set_current_user
    @current_user = User.find_by(id: session[:user_id])
    end
  
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  
  def new
    
  end
  
  def create
      @attendance = Attendance.new
      @attendance.name = params[:name]
      @attendance.email = params[:email]
      @attendance.allergy = params[:allergy]
      @attendance.book = params[:book]
      @attendance.content = params[:content]
      @attendance.come = 1
      @attendance.save
      
      redirect_to ("/attendance/thankyou")
  end 
  
  def backup
     @backups = Attendance.all
     @backup = Attendance.find(1)
  end
  
  def index
      if @current_user == nil
        redirect_to("/")
        
      else 
        @attendances = Attendance.all
      end
    
  end
  
  def thankyou
    
  end
  
  def sorry
  end
  
   def sorrysend
      @attendance = Attendance.new
      @attendance.name = params[:name]
      @attendance.come = 2
      @attendance.save
      
      redirect_to ("/canntocome/land")
   end 
   

  
  def delete
    @attendance = Attendance.find(params[:id])
    @attendance.destroy
    redirect_to ("/attendance/index")
  end
  
  def update
    @attendance = Attendance.find(params[:id])

  end
  
  def change
    @attendance = Attendance.find(params[:id])
      @attendance.name = params[:name]
      @attendance.email = params[:email]
      @attendance.allergy = params[:allergy]
      @attendance.book = params[:book]
      @attendance.content = params[:content]
      @attendance.come = params[:attendance]
      @attendance.save
      
      redirect_to ("/attendance/index")
  end
  
  
  
  def sorry_land
  end
  
end
  
  
    def list
    
    @attendances = Attendance.all
    
    @attendances_index = []
    @attendances.each do |attendance|
    @attendances_index << attendance
  end
    
   respond_to do |f|
     f.html
     f.json {render json: @attendances_index }
    end
    
  end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def login_page
    if @current_user 
        redirect_to("/land")
    end
     
  end
    
  
  def login
      @user = User.find_by(name: params[:name])
    
    if @user
      
      session[:user_id] = @user.id
      redirect_to("/land")
       
    else
      render("user/login_page")
    end
  end
  
  
  def logout
    session[:user_id] = nil
    redirect_to("/")
    
  end
  
  
  
  def new
    
    @user = User.new
    
  end
  
  def create
    
     @user = User.new
     @user.name = params[:name]
     @user.admin = params[:admin]
     @user.save
     redirect_to ("/user/index")
    
  end

  def index
    @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    if @current_user 
        redirect_to("/land")
    end
  end
  
  def land
    if @current_user == nil
        redirect_to("/")
    end
  end
    
    def place
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attendance/backup.html.erb
<% @backups.each do |attendance| %>
 
     <% end %>
     <%= @backups.each do |attendance| %>
 
     <% end %>

app/views/attendance/index.html.erb
<div class='attendance-wrapper'>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Attendance</th>
      <th scope="col">Email</th>
      <th scope="col">Book</th>
      <th scope="col">Comment</th>
      <th scope='col'>Allergy</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <% @attendances.each do |attendance| %>
  <tbody>
    <tr>
      <td><%= attendance.id %></td>
      <td><%= attendance.name %></td>
      <td><%= attendance.come %></td>
      <td><%= attendance.email %></td>
      <td><%= attendance.book %></td>
      <td><%= attendance.content %></td>
      <td><%= attendance.allergy %></td>
      <td><%= link_to "Update","/attendance/update/#{attendance.id}" %></td>
      <td><%= link_to "Delete","/attendance/delete/#{attendance.id}", method: :post, data: { confirm:"Are you sure?"} %> </td>
    </tr>
  </tbody>
  <% end %>
</table>
</div>

app/views/attendance/new.html.erb
<div class="container">

<div class="attendance-form">
<h1>Please register your info here!</h1>
<%= form_tag("/attendance/create") do %>

<p>おなまえ</p>
<input name="name"  class="form-control">

<p>メールアドレス</p>
<input name="email"  class="form-control">

<p>食べ物のアレルギーなど</p>
<input name="allergy"  class="form-control">

<p>一番好きな本/マンガ/映画/音楽</p>
<input name="book"  class="form-control">

<p>と、その理由</p>
<textarea name="content" class="form-control" rows="4"></textarea>
<p></p>

<input type="image"
src="/sankabutton.png" alt="送信"
width="165px">


<% end %>
</div>
</div>

app/views/attendance/sorry.html.erb
<div class="container">
    
<img src="/sorry.png" class="sorry">

<div class="attendance-form">
    
<%= form_tag("/attendance/sorrysend") do %>
<p>おなまえ</p>
<input name="name"  class="form-control">

<input type="submit" class="sorry-submit">

<% end %>
</div>
</div>

app/views/attendance/sorry_land.html.erb
<div class="container">
    
<img src="/sorry.png" class="sorry">

<p></p>
</div>

app/views/attendance/thankyou.html.erb
<div class="container">
    <div class="thankyou-container">
<h1 class="thankyou">Thank you</h1>
<p>ご登録ありがとうございます</p>
<p>11月11日　楽しい思い出を一緒に作ってください</p>
<p>お会いできるのが本当に楽しみです</p>
<p></p>
<p>新・千尋</p>
</div>
<img src="/dove.png" class="dove">

</div>

app/views/attendance/update.html.erb
<div class="container">

<div class="attendance-form">
<h1>Please change registration information here!</h1>
<%= form_tag("/attendance/update/#{@attendance.id}") do %>

<p>おなまえ</p>
<input name="name"  class="form-control" value="<%=@attendance.name %>">

<p>メールアドレス</p>
<input name="email"  class="form-control"  value="<%=@attendance.email %>">

<p>食べ物のアレルギーなど</p>
<input name="allergy"  class="form-control" value="<%=@attendance.allergy %>">

<p>一番好きな本/マンガ/映画/音楽</p>
<input name="book"  class="form-control" value="<%=@attendance.book %>">

<p>と、その理由</p>
<textarea name="content" class="form-control" rows="4" value="<%=@attendance.content %>"></textarea>
<p></p>

<input type='submit' value="Change">


<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wedding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <%= csrf_meta_tags %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-97562121-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-97562121-1');
</script>

</head>
<body>
<div class="background">
  <% if session[:user_id] %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span> 
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      
       <a class="navbar-brand" href="/">
        <img alt="Brand" src="/weddinglogo.png" class="nav-logo">
       </a>
       
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-content">
        <!--<li><a href="#">Attendance <span class="sr-only">(current)</span></a></li> -->
        　<li><a href="/land#page2">ごあいさつ</a></li>
         　<li><a href="/land#page3">いつ・どこで</a></li>
         　<li><a href="/land#page4">会場へのアクセス</a></li>
         　<li><a href="/land#page5">ご出欠登録</a></li>
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        -->
      </ul>
      <!--
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
      
      <ul class="nav navbar-nav navbar-right">
       <!-- <li><a href="#">Link</a></li> -->
　　　　<% if @current_user.admin? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/attendance/index">Attendance Index</a></li>
            <li><a href="/user/new">New User</a></li>
            <li><a href="/user/index">User List</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% end %>
        <li><%= link_to("ログアウト", "/logout",{method:"post"}) %></li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/user/index.html.erb
<%= session[:user_id] %>
<h1>User List</h1>

<% @users.each do |user| %>

<%= user.id %>:
<%= user.name %>, 
admin? <%= user.admin %></br>

<% end %>

app/views/user/login_page.html.erb
<div class="container">
     
     <div class="login-page">
               
       <%= form_tag("/user/login") do %>
          <img src="/key.png" class="key">
          <a>Pass:</a>
          <input name="name">
          <p></p>
          <img src="/dotline.png" class="dotline">
          <p></p>
          <input type="submit" value="Login" class="login-button">
        <% end %>
     </div>
</div>

app/views/user/new.html.erb
<div class="container">
<h1>Create User!</h1>
<!--
<#%= form_for @user, url: user_create_path do |f| %>

  <div><#%= f.text_field :name, class: "name", name="username" %></div>
  <#%= f.submit %>
<%# end %>
-->

<%= form_tag("/user/create") do %>
    <p>User</p>
    <input name="name">
    <input type="submit">
    <%= check_box_tag(:admin) %>
    <%= label_tag(:admin, "I am admin User") %> </br>
<% end %>
</div>

app/views/welcome/home.html.erb
<div class="container">
<img src="/weddinglogo.png" class="welcome-logo">
</div>
<div class="home-login">
<%= link_to("Log in","/user/login", class:"home-login-link")  %>
</div>

app/views/welcome/land.html.erb
 <div class="land-p1">
    <img src="/weddinglogo2.png" class="welcome-logo">
    </div>
 <div class="container">
 <div class="land-p2" id="page2">
    <h1>Greetings</h1>
     <div class="greeting-wrapper">
        <div class="greeting-photo">
         <img src="/chihiro-arata.gif" class="chihiro-arata">
        </div>
        <div class="greeting-message">
           <p>お互いの大切な人に、お互いを紹介できたら</p>
           <p>あとは楽しく飲んで話せたらいいなと考えています。</p>
           <p>日曜日の午後を一緒にゆったり過ごしましょう。</p>
           <p>ドレスコードはありません。（ごめんなさい、クロ―クもありません…）</p>
           <p>お気に入りのセーター、ジーンズ、スニーカーなど、</p>
           <p>あなたらしい服装で来てくださればうれしいです。</p>
   
            <p>お会いできるのを心から楽しみにしています！</p>
       </div>
      </div>
 </div>
 
 
  <div class="land-p3" id="page3">
    <h3>お久しぶりです　はじめまして</h3>
    <h1>Bride & Groom</h1>
     <div class="page3-photos">
       <img src="/chihiro-profile.gif" class="bride-grrom-photo">
       <img src="/profile_arata.gif" class="bride-grrom-photo">
     </div>
     <div class="whenwhere">
       <div class='when'>
         <h1>When</h2>
         <p>2018年11月11日</p>
         <p>12時半開場</p>
         <p>13時スタート</p>
       </div>
       <div class="where">
         <h1>Where</h2>
         <p>Lounge2343</p>
         <p>神奈川県厚木市飯山2343</p>
         <p>日比野設計さんの事務所３F</p>
       </div>
     </div>
  </div>
  
  
   <div class="land-p4" id="page4">
    <h1>Access</h1>
   <div class="acces-wrapper">
      <div class="gmap">
        <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1xQthJB6oDaOVvEUUxnbBROp7ZN08c3iU" width="440" height="440"></iframe>
      </div>
    
     <div class="access-content">
 
　　  <h3>当日はバスをだします！</h3>
      <p>※詳細は<a href="/place">こちら！</a></p>
     </div>
   </div>
 </div>
 
   <div class="land-p5" id="page5">
    <h4>ご出欠は<img src="/yes.png" class="yes-frame-samll">をクリック</h4>
    <h1>Would you come to our party?</h1>
    <a href="/attendance/new"><img src="/yes-panel.gif" class="yes-frame"></a>
    <a href="/attendance/cantcome"><img src="/sorry-panel.gif" class="yes-frame"></a>
   </div>
 

</div>

app/views/welcome/place.html.erb
<div class="container">
     <div class="bus-container">
     <h1 class="bus"> バス出します！</h1>
     <h2>12時15分ころ集合　12時30分発</h2>
     <h3>本厚木駅南口徒歩から2分　第一伊藤ビル前にお集り下さい。</h3>
   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d812.6727473077501!2d139.3633428292204!3d35.437684091426405!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzXCsDI2JzE1LjciTiAxMznCsDIxJzUwLjAiRQ!5e0!3m2!1sja!2sca!4v1540587199869" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    <h4>※バスが長時間停車できないため、時間通りに出発いたします。ご容赦くださいませ。</h4>
     
      </div>   
        
</div>